name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@0
    displayName: Build an image
  - task: Docker@0
    displayName: Push an image
    inputs:
      action: Push an image
      imageName: gcr.io/thespiders
  - task: KubernetesManifest@0
    displayName: deploy
    inputs:
      kubernetesServiceConnection: 3fdec57b-e777-4657-a0a8-fb6c389fff1b
      namespace: default
      manifests: dev.yml
      containers: http://gcr.io/thespiders
      rolloutStatusTimeout: 15
...