apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-jake
spec:
  selector:
    matchLabels:
      app: redis-stedi-jake # must match spec.template.metadata.labels
  serviceName: redis-stedi-jake
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stedi-jake
    spec:
      containers:
        - name: redis-stedi-jake
          image: redis:7.0.5-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "${REDIS_PASS}", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          env: 
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-secrets-jake
                key: REDIS_PASS
          volumeMounts:
            - name: redis-jake-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-jake-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stedi-jake
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-stedi-jake